### ISSUE TITLE
remember to update application-dev.properties for ver 7.23 

### ISSUE THREAD

**Issue by Jesper-a-sos** [business-applications/02-tutorial-business-assets-application#1]
in ver 7.23 the old naming is used "jbpm-console" replace with "business-central"
kieserver.controllers=http://localhost:8080/**business-central**/rest/controller

otherwise you get 405

**Comment by tsurdilo** [comment]
@Jesper-a-sos thanks for raising issue . here is pull request - https://github.com/business-applications/02-tutorial-business-assets-application/pull/2

**Comment by tsurdilo** [comment]
pr merged
